#!/usr/bin/env bash

# Release build is without 'test' subcommand; To build with 'test', pass 'enable-tests' argument 

ENABLE_TESTS=0

CMD=$1
NPROC=${2:-2}  # default is 2 cores

case $CMD in 
    "enable-tests")
        ENABLE_TESTS=1
        ;;
    
    *)
        ;;
esac

# Set up locale
setenv() {
    echo "LC_ALL=en_US.UTF-8" >> /etc/environment && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    echo "LANG=en_US.UTF-8" > /etc/locale.conf && \
    locale-gen "en_US.UTF-8"

    export LANG=en_US.UTF-8
    export LANGUAGE=en_US:en
    export LC_ALL=en_US.UTF-8
}

build() {
    set -e
    export CC=clang-12
    export CXX=clang++-12

    # export ASAN_OPTIONS="quarantine_size_mb=100:malloc_context_size=4:detect_leaks=0:strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:log_path=stdout"
    export CFLAGS="-O3 -g1 -fno-omit-frame-pointer"
    

    if [ $ENABLE_TESTS -eq 1 ] ; then
        echo " Build with debug & test suites"
        export CXXFLAGS="-w $CFLAGS -stdlib=libc++ -D_KINESIS"
        export CONFIGURE_FLAGS="--enable-asan --enable-extrachecks --enable-sdfprefs"
        cp pg_hba.conf /etc/postgresql/12/main/
    else 
        echo " Build for relase"
        export CXXFLAGS="$CFLAGS -stdlib=libc++ -s -DNDEBUG -D_KINESIS"
        export CONFIGURE_FLAGS="--enable-asan --enable-sdfprefs --disable-tests"
    fi

    echo "CONFIGURE_FLAGS = $CONFIGURE_FLAGS"

    ./autogen.sh
    ./configure CC="${CC}" CXX="${CXX}" CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}" ${CONFIGURE_FLAGS}
    make -j${NPROC}
    make install
}

setenv
build
